name: Com.hicupalot
version: ${project.version}
main: becomeranboo.com.hicupalot.Com.hicupalot
api-version: 1.16
authors: [ hicupalot ]
description: Become Ranboo

permissions:
  becomeranboo.Ranboo:
    description: Gives you the basic Ranboo Powers
    children:
      - becomeranboo.ender
      - becomeranboo.freezelook
      - becomeranboo.memorybook
      - becomeranboo.enderimmune
      - becomeranboo.waterdamage
  becomeranboo.silkhand:
    description: Gives you silk touch hands
  becomeranboo.ender:
    description: Makes enderman noises play
  becomeranboo.freezelook:
    description: Makes you freeze players on look
  becomeranboo.immunefreeze:
    description: makes you immmune to freezing
    default: op
  becomeranboo.memorybook:
    description: Gives you a memory book
  becomeranboo.enderimmune:
    description: Makes you immune to Ender Mobs
  becomeranboo.waterdamage:
    description: Makes you take damage in water
  becomeranboo.anticheatender:
    description: Makes it so you can't kill entities when you have the ender immune permission
