name: BecomeRanboo
version: ${project.version}
main: com.hicupalot.BecomeRanboo
api-version: 1.17
authors: [ hicupalot ]
description: Gain the Powers of DreamSMP Ranboo

commands:
  memory:
    description: "Gives you a memory book!"
    usage: /memory
    permission: becomeranboo.memorybook
permissions:
  becomeranboo.Ranboo:
    description: Gives you the basic Ranboo Powers
    children:
      - becomeranboo.ender
      - becomeranboo.freezelook
      - becomeranboo.memorybook
      - becomeranboo.enderimmune
      - becomeranboo.silkhand
  becomeranboo.silkhand:
    description: Gives you silk touch hands
  becomeranboo.ender:
    description: Gives you vulnerability to water and gives a chance for enderman sounds to play when you talk
  becomeranboo.freezelook:
    description: Makes you freeze players on look
  becomeranboo.immunefreeze:
    description: makes you immmune to freezing
    default: op
  becomeranboo.memorybook:
    description: Gives you a memory book
  becomeranboo.enderimmune:
    description: Makes you immune to Ender Mobs
  becomeranboo.dragonimmune:
    description: Makes you immune to Ender Dragons
    default-permission: op