name: Com.hicupalot
version: ${project.version}
main: becomeranboo.com.hicupalot.Com.hicupalot
api-version: 1.16
authors: [ hicupalot ]
description: Become Ranboo

permissions:
  becomeranboo.silkhand:
    description: Gives you silk touch hands
  becomeranboo.ender:
    description: Makes enderman noises play
  becomeranboo.freezelook:
    description: Makes you freeze players on look
  becomeranboo.immunefreeze:
    description: makes you immmune to freezing
    default: op
  becomeranboo.arrowdeflect:
    description: Gives you the power of the enderman arrow deflection
  becomeranboo.teleportspecific:
    description: Allows you to teleport
  becomeranboo.chat:
    description: Makes your chat ranboo-ier
  becomeranboo.chatrecieve:
    description: Receive the ranboo-ness of chat
    default: not op
  becomeranboo.memorybook:
    description: Gives you a memory book
  becomeranboo.enderimmune:
    description: Makes you immune to Ender Mobs
